spring:
  application:
    name: lve_tmst_mgmt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lveTmstMgmt
    username: root
    password: Pavan0438@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 8700
